######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 11516 2006-10-08 14:23:46Z ska $
##
######################################################################
SUBDIRS = c
RESOURCES=res/program.data.bin res/cursor.png res/white.png res/white-king.png \
          res/black.png res/tiles.png
TARGET   = cibyl-tafl.jar cibyl-tafl.jad
CIBYL_SYSCALL_SETS ?= resource_manager

include $(CIBYL_BASE)/build/Rules-j2me.mk
