######################################################################
##
## Copyright (C) 2006,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 12168 2006-11-16 12:35:57Z ska $
##
######################################################################
SUBDIRS =
TARGET  = program
OBJS    = main.o
LDLIBS  = -lc

include $(CIBYL_BASE)/build/Rules.mk
