######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 15373 2007-05-13 07:55:04Z ska $
##
######################################################################
SUBDIRS = libcrt0 libc libdebug libgcc libm libcibar libs9 libjava \
          libmidp libjsr075 libstdc++ libj2se

include $(CIBYL_BASE)/build/Rules-common.mk
