######################################################################
##
## Copyright (C) 2006,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 15074 2007-04-20 07:17:37Z ska $
##
######################################################################
SUBDIRS =
TARGET  = program
OBJS    = main.o s9_input.o
INCLUDES=-I../include
LDLIBS  = -ls9

CIBYL_MIPS2JAVA_OPTS ?=-I../include

include $(CIBYL_BASE)/build/Rules.mk
