/*********************************************************************
 *
 * Copyright (C) 2007,  Simon Kagstrom
 *
 * Filename:      basicblock.hh
 * Author:        Simon Kagstrom <simon.kagstrom@gmail.com>
 * Description:   Basic block defs
 *
 * $Id:$
 *
 ********************************************************************/
#ifndef __BASICBLOCK_HH__
#define __BASICBLOCK_HH__

#include <instruction.hh>
#include <entity.hh>

typedef enum
{
  NORMAL,
  PROLOGUE,
  EPILOGUE,
} bb_type_t;

class Function;

class BasicBlock : public CodeBlock
{
public:
  BasicBlock(Instruction **insns, bb_type_t type,
	     int first, int last);

  void setType(bb_type_t type)
  {
    this->type = type;
  }

  bool pass1();

  bool pass2();

  int fillDestinations(int *p);

  int fillSources(int *p);

  /**
   * Return the size of the generated bytecode for this instruction
   *
   * @return the estimated size in bytes of the generated bytecode
   */
  virtual size_t getBytecodeSize(void)
  {
    return this->bc_size;
  };

  virtual size_t getMaxStackHeight(void)
  {
    return this->maxStackHeight;
  };

private:
  void commentInstruction(Instruction *insn);

  void traceRegisterValues(Instruction *insn);

  void handleTables(Instruction **rtab, Instruction **wtab, Instruction *insn, bool before);

  void handleRegisterTablesPrev(Instruction **rtab, Instruction **wtab, Instruction *insn);

  void handleRegisterTablesAfter(Instruction **rtab, Instruction **wtab, Instruction *insn);

  void fillInstructionReadsAndWrites(Instruction **rtab, Instruction **wtab,
      Instruction *insn, bool before);

  void fillWriteTable(Instruction **table, Instruction *insn);

  void fillReadTable(Instruction **table, Instruction *insn);

  Instruction *lookupPrevRegister(Instruction *insn, MIPS_register_t reg,
      bool is_write);

  int n_insns;
  bb_type_t type;
  Instruction **instructions;

  size_t bc_size;
  size_t maxStackHeight;
};

#endif /* !__BASICBLOCK_HH__ */
