######################################################################
##
## Copyright (C) 2006,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:
##
## $Id: Makefile 15431 2007-05-19 11:54:12Z ska $
##
######################################################################
SUBDIRS=host-java/hello-world host-java/floating-point host-java/cpp-test \
        host-java/external-syscalls j2me/hello-world j2me/tiles-sprites j2me/sokoban \
        j2me/tafl-client j2me/events j2me/s9

include $(CIBYL_BASE)/build/Rules-common.mk
