######################################################################
##
## Copyright (C) 2006-2008,  Simon Kågström
##
## Filename:      Makefile
## Author:        Simon Kagstrom <simon.kagstrom@gmail.com>
## Description:
##
## $Id: Makefile 15431 2007-05-19 11:54:12Z ska $
##
######################################################################
SUBDIRS=host-java/hello-world host-java/floating-point host-java/cpp-test \
        host-java/exporting-java-functionality-to-cibyl host-java/file-ops \
        host-java/using-cibyl-to-export-libraries \
        j2me/hello-world j2me/tiles-sprites j2me/sokoban j2me/tafl-client j2me/events j2me/s9

include $(CIBYL_BASE)/build/Rules-common.mk
