######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 9278 2006-08-07 15:32:27Z ska $
##
######################################################################
SUBDIRS = c
RESOURCES=res/program.data.bin res/bruce.png res/tiles.png
TARGET   =midlet.jar midlet.jad
CIBYL_SYSCALL_SETS ?= resource_manager

include $(CIBYL_BASE)/build/Rules-j2me.mk
