######################################################################
##
## Copyright (C) 2005,  Blekinge Institute of Technology
##
## Filename:      Makefile
## Author:        Simon Kagstrom <ska@bth.se>
## Description:   Generic Makefile
##
## $Id: Makefile 12449 2006-11-25 16:07:55Z ska $
##
######################################################################
SUBDIRS = src/
ALL_TARGETS = crt0.o crt0-android.o crt0-qemu-debug.o
EXTRA_CLEAN=lib/*.a *.o

include $(CIBYL_BASE)/build/Rules.mk
