#!/usr/bin/env python
######################################################################
##
## Copyright (C) 2006,  Simon Kagstrom
##
## Filename:	  cibyl-generate-c-header
## Author:		Simon Kagstrom <ska@bth.se>
## Description:   Generate Java and C syscall constants
##
## $Id: cibyl-generate-c-header 13549 2007-02-09 21:19:12Z ska $
##
######################################################################
import sys, re, getopt
sys.path.append('%s/python/' % sys.path[0])
from Cibyl.SyscallHandling.syscallgenerator import *
from optparse import OptionParser

usage = """Usage: cibyl-generate-c-header [-o outdir] dir set1 [set2 ...]

Generate C headers of the system call definitions from the directory
'dir' consisting of the syscall sets 'set1', 'set2' etc. The sets are
contained within the directory 'dir', e.g., syscalls/j2me.
"""
parser = OptionParser(usage = usage)
parser.add_option("-o", "--outdir", dest="outdir", default='.',
				  help="Write output to outdir instead of current directory",
				  metavar="OUTDIR")

(options, args) = parser.parse_args()

if len(args) < 2:
	parser.error("incorrect number of arguments. Invoke with --help for arguments")

dirname = args[0]
syscallSets = args[1:]

f = SyscallHeaderGenerator(dirname, syscallSets, options.outdir)
f.run()

# And run the database generator as well
f = SyscallDatabaseGenerator(dirname, syscallSets, options.outdir + "/cibyl-syscalls.db")
f.run()
